// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0AmIiaGVCkMMYMZkC2csFf4dheA_GSFQ',
    appId: '1:869143484373:web:d0df31a2d957071eeccf5c',
    messagingSenderId: '869143484373',
    projectId: 'mailboxapplication1-f1bd9',
    authDomain: 'mailboxapplication1-f1bd9.firebaseapp.com',
    storageBucket: 'mailboxapplication1-f1bd9.appspot.com',
    measurementId: 'G-VGCQ2472X6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8mwFS_4LTFLRvTJc4J1zCVyP95Hs_swA',
    appId: '1:869143484373:android:bf549751fb938aa4eccf5c',
    messagingSenderId: '869143484373',
    projectId: 'mailboxapplication1-f1bd9',
    storageBucket: 'mailboxapplication1-f1bd9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDm7n6VG0Odvl0vJoaPMoy3bItGujJbjBY',
    appId: '1:869143484373:ios:430ca847caf38712eccf5c',
    messagingSenderId: '869143484373',
    projectId: 'mailboxapplication1-f1bd9',
    storageBucket: 'mailboxapplication1-f1bd9.appspot.com',
    androidClientId: '869143484373-9uq9s7r75ah2i19n4oeqgh5538lvmop9.apps.googleusercontent.com',
    iosClientId: '869143484373-m2fvifm7f7v4r1o1q14pqofbfehjir4l.apps.googleusercontent.com',
    iosBundleId: 'com.example.mailboxApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDm7n6VG0Odvl0vJoaPMoy3bItGujJbjBY',
    appId: '1:869143484373:ios:dad97c1aaff7f532eccf5c',
    messagingSenderId: '869143484373',
    projectId: 'mailboxapplication1-f1bd9',
    storageBucket: 'mailboxapplication1-f1bd9.appspot.com',
    androidClientId: '869143484373-9uq9s7r75ah2i19n4oeqgh5538lvmop9.apps.googleusercontent.com',
    iosClientId: '869143484373-du1r3m66d4tb3resclvctftonnem5clp.apps.googleusercontent.com',
    iosBundleId: 'com.example.mailboxApplication.RunnerTests',
  );
}
